version: '2'
services:
  web:
    build: .
    command: bundle exec rails s -b '0.0.0.0'
    working_dir: /myextjs/ProjExtjs
    volumes:
      - .:/myextjs
    ports:
      - "3000:3000"

  postgres:
    image: postgres:9.5.3
    environment:
      PGDATA: /pgdata
    ports:
      - "5432:5432"
