# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2aa8cf534f616cc2a99720f30174478850baa09bd6bf0e827399c836e6adf5a8bebe8a05cafbb235cd3790f59e5459210fa469208067c4c627c66fff6c06bfc

test:
  secret_key_base: 1c01639910b6a9a4c3b72408e2a22c9abae041e680faffdb628a7d5a2245a0f8cee2529285ebf1917ad77e4e8f1cabcd20f215af48c96379b3c395b75c18eb03

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
